[build]
  # Non serve build command, serviamo file statici
  publish = "public"
  command = "echo 'No build needed - serving static files'"

[build.environment]
  NODE_VERSION = "18"

# Headers per ottimizzare le performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache per le immagini (1 anno)
[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache per projects.json (1 ora)
[[headers]]
  for = "/projects.json"
  [headers.values]
    Cache-Control = "public, max-age=3600"
    Content-Type = "application/json"

# Redirect per compatibilità
[[redirects]]
  from = "/api/*"
  to = "/404"
  status = 404

# SPA fallback (se necessario in futuro)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}
