name: Trigger CDN Sync

on:
  push:
    branches: [main]
    paths:
      - '**/projects.json'
      - '**/screen-capture/**'

jobs:
  trigger-cdn-sync:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger CDN repository sync
        uses: peter-evans/repository-dispatch@v2
        with:
          # Ricorda che la repo che fara richiesta di trigger deve avere questo token
          token: ${{ secrets.CDN_REPO_TOKEN }}
          # Repository che andra a triggerare
          repository: ${{ github.repository_owner }}/portfolio-cdn
          # Evento che avvia il workflow
          event-type: monorepo-updated
          client-payload: |
            {
              "monorepo": "${{ github.repository }}",
              "commit": "${{ github.sha }}",
              "branch": "${{ github.ref_name }}",
              "author": "${{ github.actor }}",
              "triggered_by": "${{ github.repository }}"
            }
